# Dockerfile generated by GeneXus (.NET Core)
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
LABEL maintainer="mmoyac"
WORKDIR /app
COPY ["temp/", "/app"]
ENTRYPOINT ["dotnet", "bin/GxNetCoreStartup.dll"]
