apiVersion: apps/v1
kind: Deployment
metadata:
    name: posventagerald-deployment
    labels:
        app: posventagerald
spec:
    replicas: 1
    selector:
        matchLabels:
            app: posventagerald
    template:
        metadata:
            labels:
                app: posventagerald
        spec:
            containers:
            - name: k8s-demo10
              image: docker.io/geraldpadillaceledon/pruebadocker2:2
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: registrogerald
---
apiVersion: v1
kind: Service
metadata:
    name: posventagerald
    labels:
        app: posventagerald
spec:
    ports:
        - name: http-port
          port: 80
          targetPort: 80
    selector:
        app: posventagerald
    type: LoadBalancer
